apiVersion: apps/v1
kind: Deployment
metadata:
  name: caio-luis-recommender-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caio-luis-recommender
  template:
    metadata:
      labels:
        app: caio-luis-recommender
    spec:
      containers:
      - name: caio-luis-recommender
        image: caioalex/playlists-recommender-front:0.1
        ports:
        - containerPort: 32174