version: '3'
services:
  mlcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=model.py
      - FLASK_ENV=development
